### ISSUE TITLE
Translation Access Error

### ISSUE THREAD

**Issue by SVPA-PeterTat** [cloudyr/aws.translate#3]
I'm following the guide however i received the following error below.  I confirm that the IAM  has admin right or translation full access on 2 different AWS accounts however the same issue appears:

> translate("Hola mundo!", from = "auto", to = "en")
list()
Warning messages:
1: In translateHTTP(action = "TranslateText", body = bod, ...) :
  Bad Request (HTTP 400).
2: In structure(out$TranslatedText, SourceLanguageCode = out$SourceLanguageCode,  :
  Calling 'structure(NULL, *)' is deprecated, as NULL cannot have attributes.
  Consider 'structure(list(), *)' instead.

## session info for your system
sessionInfo()
```

**Comment by antoine-sachet** [comment]
I cannot replicate:

``` r
library("aws.translate")
translate("Hola mundo!", from = "auto", to = "en")
#> [1] "Hello world!"
#> attr(,"SourceLanguageCode")
#> [1] "es"
#> attr(,"TargetLanguageCode")
#> [1] "en"
```

<sup>Created on 2020-04-30 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Can you please edit in your `sessionInfo()` ?

AWS is refusing your request (and returns HTTP 400 "Bad Request"). Unfortunately the error message is stripped out of the output of `translate`. 

The second warning simply happens because the resulting `translatedText` is `NULL`. The real problem is the "bad request" which should admittedly be handled better.

Can you run the following and post the content of `res`?

```R
bod <- list(SourceLanguageCode = "auto",
            TargetLanguageCode = "en",
            Text = "Hola mundo!")
res <- translateHTTP(action = "TranslateText", body = bod)

# `res` will contain plenty of info, including the error message if there is one
res
```

This should give you the same error but this time we'll know why AWS is not happy.

**Comment by SVPA-PeterTat** [comment]
Sorry for the delay. This issue has been resolved.  I deleted the old aws key and regenerated a new key and that appeared to resolve the issue.  Thank you for your kind support
